import type { Metadata } from "next";
import "./globals.css";
import { spaceMono } from "@/app/UserFont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${spaceMono.className}`}>
        {children}
      </body>
    </html>
  );
}
